// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLJ-FJswpGGhoHKHORbKGpGy_XBI2JLIA',
    appId: '1:788993188947:android:66fd3ae16b69c6f6f2d2a6',
    messagingSenderId: '788993188947',
    projectId: 'arcane-shape-449219-v0',
    storageBucket: 'arcane-shape-449219-v0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzbtvlK84cadaNGXmTNZXBHRDdxdVjuU8',
    appId: '1:788993188947:ios:578a99ccccd9a7c8f2d2a6',
    messagingSenderId: '788993188947',
    projectId: 'arcane-shape-449219-v0',
    storageBucket: 'arcane-shape-449219-v0.firebasestorage.app',
    iosBundleId: 'com.beta.foxxhealth',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDldRkMYOn8uyhWcDzM3t80MEyUVZPoL5o',
    appId: '1:788993188947:web:999ca2b9fcb88243f2d2a6',
    messagingSenderId: '788993188947',
    projectId: 'arcane-shape-449219-v0',
    authDomain: 'arcane-shape-449219-v0.firebaseapp.com',
    storageBucket: 'arcane-shape-449219-v0.firebasestorage.app',
    measurementId: 'G-H9VKNVCV52',
  );

}